services:
  ratings:
    build: ratings/
    ports:
      - "8080:8080"
    environment:
      SERVICE_VERSION: v2
      MONGO_DB_URL: mongodb://mongodb:27017/ratings
      MONGO_DB_USERNAME: ratings
      MONGO_DB_PASSWORD: CHANGEME
  mongodb:
    image: bitnami/mongodb:5.0.2-debian-10-r2
    volumes:
      - "./ratings/databases:/docker-entrypoint-initdb.d"
    environment:
      MONGODB_ROOT_PASSWORD: CHANGEME
      MONGODB_USERNAME: ratings
      MONGODB_PASSWORD: CHANGEME
      MONGODB_DATABASE: ratings
  details:
    build: details/
    ports:
      - "8081:9080"
    environment:
      ENABLE_EXTERNAL_BOOK_SERVICE: "true"
  reviews:
    build: reviews/
    ports:
      - "8082:9080"
    environment:
      ENABLE_RATINGS: "true"
      RATINGS_SERVICE: http://ratings:8080
  productpage:
    build: productpage/
    ports:
      - "8083:9080"
    environment:
      DETAILS_HOSTNAME: http://details:9080
      RATINGS_HOSTNAME: http://ratings:8080
      REVIEWS_HOSTNAME: http://reviews:9080
  